# Data Science
#### By: Javier Orduz
[license-badge]: https://img.shields.io/badge/License-CC-orange
[license]: https://creativecommons.org/licenses/by-nc-sa/3.0/deed.en

[![CC License][license-badge]][license]

[![DS](https://img.shields.io/badge/downloads-DS-green)](https://github.com/Earlham-College/DS_Fall_2022)

[![Github](https://img.shields.io/badge/jaorduz-repos-blue)](https://github.com/jaorduz/)

![Follow @jaorduc](https://img.shields.io/twitter/follow/jaorduc?label=follow&logo=twitter&logoColor=lkj&style=plastic)



## Contents
1. [List and Tuples](#list_tuples)
1. [Exercises](#exercises)
1. [References](#references)

We call the package

In [8]:
import numpy as np


We create an set of random mumbers.

In [9]:
data = {i : np.random.randn(2,4) for i in range(3)}

We print the data with the label from $i= 0$ to $i= 6$

In [12]:
print(data)
print(sum(data)/len(data))

{0: array([[ 0.93615044,  0.19492984,  0.29225296,  1.04408252],
       [ 0.781249  ,  0.84167108, -0.20154998, -0.37783907]]), 1: array([[ 0.73993895, -1.47845459,  0.18005912, -0.15914035],
       [-0.37457682,  1.84774383,  1.18821744,  1.30194945]]), 2: array([[ 0.94795613, -0.26657964, -0.36841958,  1.0352666 ],
       [ 0.2435546 ,  0.74179843, -0.80437703, -0.33419249]])}
1.0


In [19]:
print(data[0])
print(sum(data[0])/len(data[0]))

[[ 0.93615044  0.19492984  0.29225296  1.04408252]
 [ 0.781249    0.84167108 -0.20154998 -0.37783907]]
[0.85869972 0.51830046 0.04535149 0.33312172]


In [20]:
print(data[0][0])
print(sum(data[0][0])/len(data[0][0]))

[0.93615044 0.19492984 0.29225296 1.04408252]
0.6168539397767603


This is how we extract the 000 element

In [22]:
data[0][0][0]

0.9361504413397479

# Exercise

1. Add documentation for the previous code, each line.
1. Calculate the average for the different columns
1. Discuss differences between List and tuples.
4. Create a Jupyter Notebook and solve this NB's questions.
5. Submmit your report in Moodle. Template https://www.overleaf.com/read/xqcnnnrsspcp